# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22e93f8ecc18636c13d912ba22dc904c32477e194a5b2db26f5365cf2bfad292818d2a371b1fe2955ede3e0e71160c818793dee19b49d7967227bc9ec42eadbe

test:
  secret_key_base: d30fbdfbce88549fcda2886e044ac1350c4087f6a4d8ccaae419eeedef8b18f6bc23dd546bd22db8650bb716651a489f73e539c24e7972f494dbee39481a1ebd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
